### ISSUE TITLE
Diference

### ISSUE THREAD

**Issue by nenads** [lucacri/spark-impersonate#1]
Hi,

im playing with this repo. Can you thell me what is differece https://github.com/KABBOUCHI/nova-impersonate i see there are more features, but i dont get it why they are added ? since impersenate has all what it needs.

example would be routes. Why they expose new nova routes when Route::impersonate(); can be used ?

BR.

**Comment by lucacri** [comment]
Hi, the reason why I made this is because Spark uses a bit of a different method to impersonate a user
